[General]
api_keys_pool_Google%20Translate%20%28Free%29=groq_secret_key_123
api_keys_pool_Groq%20Cloud%20%28Fast%29=groq_secret_key_123
api_keys_pool_NVIDIA%20NIM=nvidia_nim_key_456
cb_desc=true
cb_subs=true
cb_titles=true
concurrency_limit=3
custom_context=
model=
model_Groq%20Cloud%20%28Fast%29=canopylabs/orpheus-arabic-saudi
model_NVIDIA%20NIM=nvidia/nemotron-4-340b-instruct
policy=Full Overwrite (Перезаписать)
provider=NVIDIA NIM
target_lang=ru_ru
