name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyinstaller
      - run: pip install -r requirements.txt
      - run: pyinstaller --onefile --noconsole --icon=resources/logo.png --add-data "resources;resources" main.py --name snbt-tr
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/snbt-tr.exe
