name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyinstaller pillow
      - run: pip install -r requirements.txt
      - run: pyinstaller --onefile --noconsole --icon=resources/logo.png --add-data "resources;resources" main.py --name snbt-tr
      - run: |
          & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" setup.iss
        shell: pwsh
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/snbt-tr.exe
            snbt-tr-Windows-Installer.exe
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: "ronnikols.snbt-tr"
          installers-regex: "snbt-tr-Windows-Installer\\.exe$"
          token: "${{ secrets.WINGET_TOKEN }}"
